controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


redirect_home:
    path: /
    controller: App\Controller\HomeController::redirectToHome

//tet